### ISSUE TITLE
[HVDC] Initial state of HVDC not taken into account

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#2733] opened 2023-01-17 09:01 UTC
When the HVDC link is not connected (disconnector and breaker open) at the beginning of the calculation, it is closed at the end of it, with a Q injection.

One possible explanation is that the initial state of the HVDC is not read.

**Comment by rosiereflo** [comment] 2023-01-25 14:22
It is a platform bug that is now fixed: it was caused by the fact that a Modelica HVDC model was used even if the line was disconnected initially

**Closed by rosiereflo** 2023-01-25 14:22 UTC
Labels: Bug, Models library, DynaWaltz
