### ISSUE TITLE
when considering cpp models, in getY0 we should check if starting from dump 

### ISSUE THREAD

**Issue by marcochiaramello** [dynawo/dynawo#2131] opened 2022-01-27 08:34 UTC
In many cpp models, when starting from dump, getY0 is called with default values not considering the ones in dump. This brings to small inconsistencies and precision errors.

**Comment by rosiereflo** [comment] 2022-01-28 09:39
duplicate of #1845

**Closed by rosiereflo** 2022-01-28 09:39 UTC
Labels: Bug, Won't fix, Accuracy, Initialization
