### ISSUE TITLE
Add another initialization strategy for the network model

### ISSUE THREAD

**Issue by adriguir** [dynawo/dynawo#1264] opened 2020-11-18 09:02 UTC
In the current state, the initialization strategy for the network does the assumption that a previous calculation has been done and that P and Q attributes from the IIDM are set.
If it is not the case, the currents on two-ports structures are zero at the beginning of the global initialization, leading to a more complex and different calculation there.
Another strategy using values of V,Theta can be easily done, at least for lines and transformers.

**Comment by rosiereflo** [comment] 2022-06-21 09:06
Is this a duplicate of #2366 ?

**Closed** 2022-09-15 13:01 UTC
Labels: Enhancement, Models library, On-hold
